apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: '$.ns'
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: api
      containers:
        - name: api
          image: k3env/sample-auth:$.tag
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: api
          volumeMounts:
            - mountPath: /app/pki
              name: secrets
          ports:
            - containerPort: 8000
